# -*- coding: utf-8 -*-
"""Copy of matches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKqGy-BrNm6zCbMHRt5WVlet30GAOfke
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("matches_full.csv")

print(df.columns.tolist())

df.drop(columns=['notes'], inplace=True, errors='ignore')

print(df.shape)              # Number of rows and columns

print(df.columns)            # Column names

print(df.head())             # First few rows

print(df.describe())

print(df.describe(include='object'))

print(df.info())

"""Missing Value"""

missing_values = df.isnull().sum()
print(missing_values)

"""Mean , min , max"""

num_summary = df.describe().loc[['mean', 'min', 'max']]
print(num_summary)

"""Data type"""

print(df.dtypes)

def count_outliers(column):
    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return ((df[column] < lower) | (df[column] > upper)).sum()

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
outliers = {col: count_outliers(col) for col in numeric_cols}
print("\nOutlier Counts:\n", outliers)



"""Column relationships"""

df[numeric_cols].hist(bins=15, edgecolor='black', color='skyblue', figsize=(16, 12))
plt.suptitle("Data Distribution for Numeric Columns", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""Categorical columns Number

"""

categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("Categorical columns:", list(categorical_cols))
print("Number of categorical columns:", len(categorical_cols))

# 5. Correlation Matrix
correlation_matrix = df.select_dtypes(include=['float64', 'int64']).corr()
print("\nCorrelation Matrix:\n", correlation_matrix)

# 3. Number of Categorical Columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("\nNumber of Categorical Columns:", len(categorical_cols))

# 2. Box Plot of 'gf' (Goals For)
plt.figure()
sns.boxplot(data=df, y='gf', color='lightgreen')
plt.title("Box Plot of Goals Scored (gf)")
plt.ylabel("Goals For")
plt.show()

# 3. Scatter Plot of xG vs Goals Scored
plt.figure()
sns.scatterplot(data=df, x='xg', y='gf', hue='venue')
plt.title("xG vs Goals Scored")
plt.xlabel("Expected Goals (xG)")
plt.ylabel("Goals Scored (gf)")
plt.show()

# Choose a target column to compare against
target_col = 'gf'  # You can also use 'xg' or others

# Loop through numeric columns
for col in numeric_cols:
    if col == target_col:
        continue  # skip plotting against itself

    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df, x=col, y=target_col, hue='venue', palette='Set2')
    plt.title(f"Scatter Plot: {col} vs {target_col}", fontsize=14)
    plt.xlabel(col)
    plt.ylabel(target_col)
    plt.tight_layout()
    plt.show()

target_col = 'gf'
categorical_cols = ['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'opponent',
                    'captain', 'formation', 'opp formation', 'referee', 'match report', 'team']

for col in categorical_cols:
    plt.figure(figsize=(12, 6))
    sns.boxplot(data=df, x=col, y=target_col)
    plt.title(f"Boxplot: {target_col} by {col}")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# 4. Bar Plot: Average xG per Opponent (Top 10 opponents by frequency)
top_opponents = df['opponent'].value_counts().head(10).index
avg_xg = df[df['opponent'].isin(top_opponents)].groupby('opponent')['xg'].mean().sort_values()
plt.figure()
avg_xg.plot(kind='barh', color='coral')
plt.title("Average xG per Opponent (Top 10)")
plt.xlabel("Average xG")
plt.show()

# 5. Line Plot: Goals scored per season
season_goals = df.groupby('season')['gf'].sum()
plt.figure()
season_goals.plot(marker='o', linestyle='-', color='purple')
plt.title("Goals Scored per Season")
plt.xlabel("Season")
plt.ylabel("Goals")
plt.grid(True)
plt.show()

# 4. Heatmap: Correlation between numeric features
plt.figure(figsize=(10, 8))
sns.heatmap(df.select_dtypes(include=['float64', 'int64']).corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

# 1. Histogram of 'xg' (Expected Goals)
plt.figure()
df['xg'].hist(bins=30, color='skyblue', edgecolor='black')
plt.title("Distribution of Expected Goals (xG)")
plt.xlabel("xG")
plt.ylabel("Frequency")
plt.show()

# 7. Density Plot for 'xg'
plt.figure()
sns.kdeplot(df['xg'].dropna(), fill=True, color='dodgerblue')
plt.title("Density Plot of Expected Goals (xG)")
plt.xlabel("xG")
plt.show()

# 6. Heatmap: Correlation Matrix
plt.figure(figsize=(10, 6))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

for col in categorical_cols:
    plt.figure(figsize=(10,5))
    sns.countplot(data=df, x=col, order=df[col].value_counts().index)
    plt.xticks(rotation=45)
    plt.title(f"Countplot of {col}")
    plt.tight_layout()
    plt.show()

for col in categorical_cols:
    plt.figure(figsize=(10,5))
    order = df.groupby(col)[target_col].mean().sort_values().index
    sns.barplot(data=df, x=col, y=target_col, order=order)
    plt.xticks(rotation=45)
    plt.title(f"Average {target_col} by {col}")
    plt.tight_layout()
    plt.show()

# Example: average target by date (if date is datetime)
df['date'] = pd.to_datetime(df['date'])

time_col = 'date'
df_sorted = df.sort_values(time_col)
plt.figure(figsize=(12,6))
sns.lineplot(data=df_sorted, x=time_col, y=target_col)
plt.title(f"Trend of {target_col} over {time_col}")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,8))
corr = df[numeric_cols].corr()

plt.title("Correlation Matrix")

# Set specific value (both [row, col] and [col, row]) to NaN
if corr.loc['poss', 'xg'] == 0.30:
    corr.loc['poss', 'xg'] = np.nan
    corr.loc['xg', 'poss'] = np.nan  # make symmetric

sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")

plt.show()

plt.figure(figsize=(10, 8))

# Compute correlation matrix
corr = df[numeric_cols].corr()

# Check actual value (optional debug)
print("Correlation between poss and xg:", corr.loc['poss', 'xg'])

# Replace the value with NaN if it's approximately 0.3
if np.isclose(corr.loc['poss', 'xg'], 0.3, atol=0.01):  # or change atol to 0.001 for stricter match
    corr.loc['poss', 'xg'] = np.nan
    corr.loc['xg', 'poss'] = np.nan  # Make symmetric

if np.isclose(corr.loc['gf', 'sh'], 0.25, atol=0.01):  # or change atol to 0.001 for stricter match
    corr.loc['gf', 'sh'] = np.nan
    corr.loc['gf', 'sh'] = np.nan

if np.isclose(corr.loc['gf', 'pkatt'], 0.25, atol=0.01):  # or change atol to 0.001 for stricter match
    corr.loc['gf', 'pkatt'] = np.nan
    corr.loc['gf', 'pkatt'] = np.nan

if np.isclose(corr.loc['gf', 'pk'], 0.27, atol=0.01):  # or change atol to 0.001 for stricter match
    corr.loc['gf', 'pk'] = np.nan
    corr.loc['gf', 'pk'] = np.nan

if np.isclose(corr.loc['pk', 'gf'], 0.27, atol=0.01):  # or change atol to 0.001 for stricter match
    corr.loc['pk', 'gf'] = np.nan
    corr.loc['pk', 'gf'] = np.nan

if np.isclose(corr.loc['pkatt', 'gf'], 0.25, atol=0.01):  # or change atol to 0.001 for stricter match
    corr.loc['pkatt', 'gf'] = np.nan
    corr.loc['pkatt', 'gf'] = np.nan
# Plot heatmap with NaNs (blank)
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", mask=corr.isnull())

plt.title("Correlation Matrix (with poss vs xg ~0.3 removed)")
plt.show()

plt.figure(figsize=(10, 8))

# Compute correlation matrix
corr = df[numeric_cols].corr()

# Define correlations you want to remove:
# Format: (row, column, target_value)
to_remove = [
    ('poss', 'xg', 0.30),
    ('gf', 'sh', 0.25),
    ('gf', 'pkatt', 0.25),
    ('gf', 'pk', 0.27),
    ('pk', 'gf', 0.27),
    ('pkatt', 'gf', 0.25),
    ('fk','sh',0.23),
    ('dist','fk',0.21),
    ('sot','poss',0.28),
]

# Tolerance for "approximately equal"
tolerance = 0.01

# Loop through and remove the values
for row, col, val in to_remove:
    if np.isclose(corr.loc[row, col], val, atol=tolerance):
        corr.loc[row, col] = np.nan
    if np.isclose(corr.loc[col, row], val, atol=tolerance):  # symmetric
        corr.loc[col, row] = np.nan

# Plot heatmap with NaNs masked
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", mask=corr.isnull())
plt.title("Correlation Matrix (Selected Values Removed)")
plt.show()

for col in numeric_cols:
    plt.figure(figsize=(8,5))
    sns.kdeplot(df[col], shade=True)
    plt.title(f"Density Plot of {col}")
    plt.tight_layout()
    plt.show()

sns.pairplot(df[numeric_cols])
plt.suptitle("Pairplot of Numeric Features", y=1.02)
plt.show()