# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLc7gZaRVtY6cPSZj8mEYmfEzgI4essL
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("Titanic-Dataset.csv")

print(df.shape)              # Number of rows and columns

print(df.columns)            # Column names

print(df.head())             # First few rows

print(df.describe())         # Summary for numerical columns

print(df.describe(include='object'))

print(df.info())

"""Missing Value"""

missing_values = df.isnull().sum()
print(missing_values)

"""Mean , min , max"""

num_summary = df.describe().loc[['mean', 'min', 'max']]
print(num_summary)

"""Data type"""

print(df.dtypes)

"""Column relationships"""

sns.pairplot(df.select_dtypes(include=['float64', 'int64']).dropna())
plt.show()

"""Categorical columns Number

"""

categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("Categorical columns:", list(categorical_cols))
print("Number of categorical columns:", len(categorical_cols))

num_cols = df.select_dtypes(include=['float64', 'int64']).columns

for col in num_cols:
    plt.figure(figsize=(6, 3))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()