# -*- coding: utf-8 -*-
"""Feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3n1z50FFpmbbvtMWdhREl0QPr9YHYhe
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, PolynomialFeatures

"""Load data"""

df = pd.read_csv("nyc-rolling-sales.csv")

print(df.head())

"""Clean numeric fields"""

df['SALE PRICE'] = pd.to_numeric(df['SALE PRICE'], errors='coerce')
df['LAND SQUARE FEET'] = pd.to_numeric(df['LAND SQUARE FEET'].astype(str).str.replace(',', ''), errors='coerce')
df['GROSS SQUARE FEET'] = pd.to_numeric(df['GROSS SQUARE FEET'].astype(str).str.replace(',', ''), errors='coerce')
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'], errors='coerce')

"""Print updated dtypes to verify conversions"""

print("Column Data Types After Cleaning:\n")
print(df[['SALE PRICE', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'SALE DATE']].dtypes)

"""Print a few sample rows to see the results"""

print("\nSample Rows After Cleaning:\n")
print(df[['SALE PRICE', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'SALE DATE']].head(10))

"""Filter valid data"""

df = df[df['SALE PRICE'].notna() & (df['SALE PRICE'] > 0)]
df = df.dropna(subset=['LAND SQUARE FEET', 'GROSS SQUARE FEET']).reset_index(drop=True)

"""Feature Selection via correlation"""

numeric_cols = df.select_dtypes(include=[np.number])
correlations = numeric_cols.corr()['SALE PRICE'].sort_values(ascending=False)
selected_features = correlations[1:6].index.tolist()  # Exclude SALE PRICE itself

"""Log Transformation"""

df['LOG SALE PRICE'] = np.log1p(df['SALE PRICE'])

"""Polynomial Features"""

df['BUILDING AGE'] = 2024 - df['YEAR BUILT']
poly = PolynomialFeatures(degree=2, include_bias=False)
poly_features = poly.fit_transform(df[['BUILDING AGE']])
poly_df = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(['BUILDING AGE']))
df = pd.concat([df, poly_df], axis=1)

"""Feature Creation"""

df['PRICE PER UNIT'] = df['SALE PRICE'] / df['TOTAL UNITS'].replace(0, np.nan)
df['PRICE PER SQFT'] = df['SALE PRICE'] / df['GROSS SQUARE FEET'].replace(0, np.nan)
df['HAS_COMMERCIAL'] = (df['COMMERCIAL UNITS'] > 0).astype(int)

"""Feature Extraction from ADDRESS"""

df['ADDRESS_LEN'] = df['ADDRESS'].str.len()

"""Label Encoding for BOROUGH"""

le = LabelEncoder()
df['BOROUGH_ENC'] = le.fit_transform(df['BOROUGH'])

"""One-hot Encoding for top 5 NEIGHBORHOODs"""

top_5 = df['NEIGHBORHOOD'].value_counts().nlargest(5).index
df['NEIGHBORHOOD_TOP5'] = df['NEIGHBORHOOD'].apply(lambda x: x if x in top_5 else 'Other')
df = pd.get_dummies(df, columns=['NEIGHBORHOOD_TOP5'], prefix='NEIGHBORHOOD')

"""Standardization and Normalization"""

scaler_std = StandardScaler()
scaler_norm = MinMaxScaler()

df['SALE PRICE STD'] = scaler_std.fit_transform(df[['SALE PRICE']])
df['SALE PRICE NORM'] = scaler_norm.fit_transform(df[['SALE PRICE']])

""" Preview"""

print(df[[
    'SALE PRICE', 'LOG SALE PRICE', 'BUILDING AGE',
    'PRICE PER UNIT', 'PRICE PER SQFT', 'HAS_COMMERCIAL',
    'ADDRESS_LEN', 'BOROUGH_ENC', 'SALE PRICE STD', 'SALE PRICE NORM'
] + [col for col in df.columns if col.startswith('NEIGHBORHOOD_')]].head())