# -*- coding: utf-8 -*-
"""Newyork1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181XmJqrVsuuI-2pErCGQw9fbOOMcwTTr
"""

# pandas: For data loading and manipulation.
# numpy: For numerical operations and filtering.
# matplotlib and seaborn: For generating static, animated, and interactive plots.
# IPython.display: To improve output formatting in notebooks.


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

# Data Loading
# This ensures that once the Visualization class is instantiated, the dataset is ready for all subsequent operations.


class Visualization:
    def __init__(self):
        self.df = pd.read_csv('/content/nyc-rolling-sales.csv')
        print("Dataset loaded successfully. Shape:", self.df.shape)

        Data Analysis Pipeline

# Print the first few rows of the dataset.
# Display the overall shape (rows × columns).
# Show column names.
# This gives a quick overview of the dataset structure.

    def initial_inspection(self):
        print("\n--- Initial Data Inspection ---")
        display(self.df.head())
        print("\nShape of Data:", self.df.shape)
        print(self.df.columns.tolist())
# Print statistical summary of all numeric columns (mean, std, min, max).
# Show frequency-based description of categorical columns.
# Provides insight into data distribution and potential anomalies.

    def descriptive_statistics(self):
        print("\n--- Descriptive Statistics for Numerical Columns ---")
        display(self.df.describe())
        print("\n--- Descriptive Statistics for Categorical Columns ---")
        display(self.df.describe(include='object'))


# Identify columns with missing data.
# Display only those with null counts greater than 0.
# Understanding missing data is critical for effective preprocessing and modeling.

    def check_missing_values(self):
        print("\n--- Missing Values ---")
        missing = self.df.isnull().sum()
        display(missing[missing > 0])

# Calculate correlations between numeric features.
# Visualize correlation matrix using a heatmap.
# : Helps identify multicollinearity and strong associations between features.


    def correlation_matrix(self):
        print("\n--- Correlation Matrix ---")
        numeric_cols = self.df.select_dtypes(include=np.number)
        corr = numeric_cols.corr()
        display(corr)
        plt.figure(figsize=(10, 8))
        sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
        plt.title("Correlation Matrix")
        plt.show()


# Generate histograms of all numeric features.
# : Visualizing distributions helps detect skewness, outliers, and spread.

    def data_distributions(self):
        print("\n--- Data Distributions ---")
        numeric_cols = self.df.select_dtypes(include=np.number).columns
        self.df[numeric_cols].hist(bins=15, figsize=(15, 10), layout=(4, 4))
        plt.tight_layout()
        plt.show()


# Create scatter plots comparing each numeric feature to the last numeric column.
# : Useful for spotting linear or nonlinear trends and potential relationships.

    def scatter_plots(self):
        print("\n--- Scatter Plots ---")
        numeric_cols = self.df.select_dtypes(include=np.number).columns
        if len(numeric_cols) < 2:
            print("Not enough numerical columns for scatter plots.")
            return
        for i, col in enumerate(numeric_cols[:-1]):
            plt.figure(figsize=(6, 4))
            sns.scatterplot(data=self.df, x=col, y=numeric_cols[-1])
            plt.title(f"Scatter Plot: {col} vs {numeric_cols[-1]}")
            plt.show()


# Create bar plots of the top 10 most frequent values for each categorical column.
# : Analyzing category distributions helps detect class imbalance and rare classes.


    def bar_charts(self):
        print("\n--- Bar Charts ---")
        cat_cols = self.df.select_dtypes(include='object').columns
        for col in cat_cols:
            plt.figure(figsize=(8, 4))
            self.df[col].value_counts().head(10).plot(kind='bar')
            plt.title(f"Bar Chart of {col}")
            plt.xlabel(col)
            plt.ylabel("Count")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.show()


# Plot box plots for all numeric columns.
# : Detects outliers, distribution spread, and quartiles visually.


    def box_plots(self):
        print("\n--- Box Plots ---")
        numeric_cols = self.df.select_dtypes(include=np.number).columns
        for col in numeric_cols:
            plt.figure(figsize=(6, 4))
            sns.boxplot(y=self.df[col])
            plt.title(f"Box Plot of {col}")
            plt.show()


# Plot Kernel Density Estimates (smoothed histograms) for numeric features.
# : Better visualization of underlying distributions, particularly for skewed data.

    def density_plots(self):
        print("\n--- Density Plots ---")
        numeric_cols = self.df.select_dtypes(include=np.number).columns
        for col in numeric_cols:
            plt.figure(figsize=(6, 4))
            sns.kdeplot(data=self.df, x=col, fill=True)
            plt.title(f"Density Plot of {col}")
            plt.show()

# Visualize the relationship between the target column and all other features.
# Numeric vs. Target → Box plots
# Categorical vs. Target → Count plots
# : Crucial for understanding how features vary across different classes or outcomes.

    def analyze_target_relationship(self, target):
        print(f"\n--- Relationship of Target '{target}' with Other Columns ---")
        for col in self.df.columns:
            if col == target:
                continue
            plt.figure(figsize=(6, 4))
            if self.df[col].dtype in ['int64', 'float64']:
                sns.boxplot(x=self.df[target], y=self.df[col])
                plt.title(f"{target} vs {col} (Box Plot)")
            else:
                sns.countplot(data=self.df, x=col, hue=self.df[target])
                plt.title(f"{target} vs {col} (Count Plot)")
                plt.xticks(rotation=45, ha = 'right')
            plt.tight_layout()
            plt.show()

#Executes the entire EDA pipeline in order.
# Includes target relationship analysis if a target is specified.
# : Provides a comprehensive, one-stop function to run all EDA steps in sequence.

    def full_analysis(self, target=None):
        self.initial_inspection()
        self.descriptive_statistics()
        self.check_missing_values()
        self.correlation_matrix()
        self.data_distributions()
        self.scatter_plots()
        self.bar_charts()
        self.box_plots()
        self.density_plots()
        if target:
            self.analyze_target_relationship(target)

# Once the Visualization class is defined, you can create an instance and invoke any method as needed.
# This provides flexibility to perform specific analysis tasks or run the full EDA pipeline with an optional target column.


viz = Visualization()
viz.initial_inspection()
viz.descriptive_statistics()
viz.check_missing_values()
viz.correlation_matrix()
viz.data_distributions()
viz.scatter_plots()
viz.bar_charts()
viz.box_plots()
viz.density_plots()

#viz.full_analysis(target='BUILDING CLASS CATEGORY')  # Optional: use a real target column